### ISSUE TITLE
Sorry I just needed to know.

### ISSUE THREAD

**Issue by MrMindels** [rohan23chhabra/p2p#1]
Hi there so sorry for the issue report but sadly Github does not have a DM system. 
I just had to know if this project was inspired by Silicon Valley the series as I have not seen many p2p file sharing
projects.

thanks in advanced and have a good day 😄

**Comment by rohan23chhabra** [comment]
Hey @AugmentedPhoenix 

I am seeing your message today. Somehow, I missed it. Apologies for that.

To answer your question, no this project isn't inspired by any TV series. I haven't even watched Silicon Valley LOL. This project just served as a learning project for me when I was in my third year as I wanted to build something apart from the standard client-server model.

This is when I learnt a bit about P2P networking and gave this project a try.

I am planning to improve this project in a few months time as I have matured a lot as a software developer.
